### ISSUE TITLE
Focus the curriculum on version control/github and its application to work

### ISSUE THREAD

**Issue by pythagoraswitch** [BITSS/WorldBankNov2016#1]
@garretchristensen : 
I think the lesson learned from [the April workshop](https://github.com/BITSS/WorldBankApril2016) is we covered too many topics in short time. Our current priority is to get the audience familiarized with GitHub and version control, so I'd not put emphasis on (or even take out) Stata + R contents. 

I'd structure the workshop like this (not necessarily in this order):
#### Afternoon hands-on session
+ Version control concept and benefits, GitHub as a platform
+ How they can apply these into their work/research with specific examples
+ Basic step-by-steps, create a repo and commit files, diff, etc.
+ Hands-on session (edit a file together in each table group, etc) with helpers walking around
+ Wrapping up & hearing participants' thoughts on how they can integrate this into their workflows.

#### Morning informational session
+ Motivational lightning talks (we can arrange people for this)
+ A session to introduce how to get started with GitHub account at the World Bank and introduce some of the projects going on at the Bank's organizational account. (I can do this)
+ "GitHub for TTLs", focusing on collaboration aspect, for staffs mainly supervising RAs and technical developers for their projects. -> this could potentially be a parallel session in the afternoon. (I can do this)

**Comment by garretchristensen** [comment]
@pythagoraswitch 
Seems fine to me to cut down the amount of material. 
I'm a little concerned about being stuck with Github Desktop, since there's so little help information available online (just [this](https://help.github.com/desktop/guides/contributing/)) and it's also limited in its capabilities--I'm pretty sure you can't resolve conflicts or anything. Will Windows users also have Git Bash installed? I find it much nicer to use than the Git Shell that comes when you install Github Desktop on a Windows machine.

I'm also a little concerned about all the collaboration stuff inherent to Github.com. I'm less familiar with that since I don't contribute to large open source projects.

Also, will attendees have access to private repositories? I'm not sure everyone is going to immediately want to share all their insider discussions about details of their code.

**Comment by pythagoraswitch** [comment]
Sounds good! 
+ As discussed, you can mix in the git bash (while participants use git shell) for conflict resolving, etc. You can assume that the participants will have GitHub Desktop installed, but not necessarily Git bash at this point. 
+ I'm going to cover the part inherent to github.com in the GitHub for TTLs session.
+ We will have participants become a member of [World Bank organizational account](https://github.com/worldbank), and I will prepare a sandbox private repo for participants to play around with. I will add you as external collaborator so you can push whatever the hands-on session starter materials you are going to use.

How about the agenda below? (You can budget the afternoon session in whatever the way you'd like)

time | session | who
------------ | ------------- | -------------
9:30-10am | Welcome and introductions, setting things up | 
10-10:45am | motivational talks | TBD, 2-3 speakers
10:45-11am | COFFEE BREAK |
11-11:30 | How to get started with World Bank GitHub account | Kiwako/Andrew
11:30-12:30pm | GitHub for TTLs - How to use GitHub as a collaboration and project monitoring tool | Kiwako/Andrew
12:30-1:30pm | LUNCH BREAK |
1:30-2:45pm | Version control part 1 | Garret
2:45-3pm| COFFEE BREAK |
3-4:30pm | Version control part 2; including group work (hands-on session) | Garret
4:30-5pm | Closing discussion | Garret and Kiwako

I still want the following to be covered in the version control sessions:
+ Version control concept and benefits
+ How they can apply these into their work/research with specific examples
+ Step-by-steps of the workflow, create a repo and commit files, diff, branch, resolve conflicts, etc.
+ Hands-on session (edit a file together in each table group, etc) with helpers walking around

**Comment by garretchristensen** [comment]
For introductions I'd like a solid 30 minutes to do slides on transparency and reproducibility in general, so the first 45 minutes should be intro to have me, you, and attendees all introduce selves.

I'd also think that the Github for TTL session should be at the end--makes more sense for people to learn the intricacies of the website *after* they learn the basics of version control, I think.

**Comment by pythagoraswitch** [comment]
@garretchristensen Sounds good! For introductions, I was also thinking you could be part of the motivational talk speaker. To make things clear and create more space, how about below?

time | session | who
------------ | ------------- | -------------
9:30-9:45 | Welcome and introductions | everyone
9:45-10:45 | motivational talks: (1) Intro to transparency and reproducibility by Garret (30mins), followed by 1-2 speakers | Garret + TBD
10:45-11 | COFFEE BREAK |
11-12:15 | Version control part 1 | Garret
12:15-1:15pm | LUNCH BREAK |
1:15-2:45 | Version control part 2; including group work (hands-on session) | Garret
2:45-3 | COFFEE BREAK |
3-3:30 | How to get started with World Bank GitHub account | Kiwako/Andrew
3:30-4:30 | GitHub for TTLs - How to use GitHub as a collaboration and project monitoring tool | Kiwako/Andrew
4:30-5 | Closing discussion | Garret and Kiwako

**Comment by garretchristensen** [comment]
Agenda looks solid to me. Do you have anybody lined up for a lightning talk?

**Comment by pythagoraswitch** [comment]
yep! The agenda is now like this:

time | session | who
------------ | ------------- | -------------
9:30-10:15 | Welcome and introductions; Transparency and Reproducibility in social science research | Kiwako + Garret
10:15-10:45 | motivational talks - why version control? | Jamie (GitHub Government Team); Tariq (World Bank Global Data Editor)
10:45-11 | COFFEE BREAK |
11-12:15 | Version control part 1 | Garret
12:15-1:15pm | LUNCH BREAK |
1:15-2:45 | Version control part 2; including group work (hands-on session) | Garret
2:45-3 | COFFEE BREAK |
3-3:30 | How to get started with World Bank GitHub account | Kiwako + Andrew
3:30-4:30 | GitHub for TTLs - How to use GitHub as a collaboration and project monitoring tool | Kiwako + Andrew
4:30-5 | Closing discussion | Garret + Kiwako
